# Deployment object
deployment:
  enabled: true
  name: orders
  namespace: cattle-monitoring-system
  replicas: 1
  appName: orders
  role: api
  containerName: orders-container
  imageRepository: sonubj/microservicessssss
  imageTag: 0.3.17
  port: 3003
