# Deployment object
deployment:
  enabled: true
  name: orders
  namespace: ecommerce
  replicas: 1
  appName: orders
  role: api
  containerName: orders-container
  imageRepository: sonubj/microservices
  imageTag: 0.3.13
  port: 3003
