# Deployment object
deployment:
  enabled: true
  name: orders
  namespace: ecommerce
  replicas: 1
  appName: orders
  role: api
  containerName: orders-container
  imageRepository: sonubj/microservices
  imageTag: sha256:9ed36b6b3b97e9af28cce1b99c7c9a1af0c32075456439b0303cb22a4a05cfb2
  port: 3003
