# Deployment object
deployment:
  enabled: true
  name: orders
  namespace: ecommerce
  replicas: 1
  appName: orders
  role: api
  containerName: orders-container
  imageRepository: sonubj/microservices
  imageTag: 0.3.1
  port: 3003
# Horizontal Pod Autoscaler
hpa:
  enabled: true
  name: orders-hpa
  namespace: ecommerce
# Service object
